

-- Drop all tables in the database
DO $$ 
DECLARE 
    r RECORD;
BEGIN 
    FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
        EXECUTE 'DROP TABLE IF EXISTS ' || quote_ident(r.tablename) || ' CASCADE';
    END LOOP; 
END $$;

CREATE TYPE troop_type AS ENUM ('BTROOP', 'GTROOP', 'MTROOP');



CREATE TABLE IF NOT EXISTS public."CAMP_DPMT"
(
    "DPMT_ID" uuid NOT NULL DEFAULT gen_random_uuid(),
    "DPMT_NAME" varchar(50) NOT NULL,
    "DPMT_HEAD_ID" uuid,
    "CRTN_DATE" timestamp with time zone NOT NULL DEFAULT now(),
    "LAST_UPTD_DATE" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "CAMP_DPMT_PKEY" PRIMARY KEY ("DPMT_ID")
);

CREATE TABLE IF NOT EXISTS public."EMPLOYEE"
(
    "EMP_ID" uuid NOT NULL DEFAULT gen_random_uuid(),
    "EMP_FIRST_NAME" varchar(150) NOT NULL,
    "EMP_LAST_NAME" varchar(150)	NOT NULL,
    "EMP_PHONE_NMBR" varchar(20),
    "DPMT_ID" uuid NOT NULL,
    "CRTN_DATE" timestamp with time zone NOT NULL DEFAULT now(),
    "LAST_UPTD_DATE" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "EMPLOYEE_PKEY" PRIMARY KEY ("EMP_ID")
);

CREATE TABLE IF NOT EXISTS public."TROOP"
(
    "TROOP_ID" uuid NOT NULL DEFAULT gen_random_uuid(),
    "TROOP_NMBR" integer NOT NULL,
	"TROOP_PHONE_NMBR" varchar(20),
	"TROOP_EMAIL" varchar(80) NOT NULL,
	"TROOP_TYPE" troop_type NOT NULL,
	"TROOP_CITY" varchar(150) NOT NULL,
	"TROOP_STATE" char(2) NOT NULL,
    "CRTN_DATE" timestamp with time zone NOT NULL DEFAULT now(),
    "LAST_UPTD_DATE" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "TROOP_PKEY" PRIMARY KEY ("TROOP_ID")--,
    --CONSTRAINT troop_troop_number_key UNIQUE (troop_number) Troop number may not be unique, further research required
);

CREATE TABLE IF NOT EXISTS public."SCOUT_LEADER"
(
    "SCOUT_LEADER_ID" uuid NOT NULL DEFAULT gen_random_uuid(),
    "SCOUT_LEADER_FIRST_NAME" varchar(150) NOT NULL,
    "SCOUT_LEADER_LAST_NAME" varchar(150) NOT NULL,
    "TROOP_ID" uuid NOT NULL,
    "TROOP_LEADER_PHONE_NMBR" varchar(20),
    "TROOP_LEADER_EMAIL" varchar(80),
    "CRTN_DATE" timestamp with time zone NOT NULL DEFAULT now(),
    "LAST_UPTD_DATE" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "SCOUT_LEADER_PKEY" PRIMARY KEY ("SCOUT_LEADER_ID")
);

CREATE TABLE IF NOT EXISTS public."SCOUT"
(
    "SCOUT_ID" uuid NOT NULL DEFAULT gen_random_uuid(),
    "SCOUT_FIRST_NAME" varchar(150) NOT NULL,
    "SCOUT_LAST_NAME" varchar(150) NOT NULL,
    "TROOP_ID" uuid NOT NULL,
    "CRTN_DATE" timestamp with time zone NOT NULL DEFAULT now(),
    "LAST_UPTD_DATE" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "SCOUT_PKEY" PRIMARY KEY ("SCOUT_ID")
);

CREATE TABLE IF NOT EXISTS public."MERIT_BADGE"
(
    "BADGE_ID" uuid NOT NULL DEFAULT gen_random_uuid(),
    "BADGE_NAME" varchar(150) NOT NULL,
    "BADGE_DESC" text COLLATE pg_catalog."default",
    "EAGLE_BADGE" boolean NOT NULL DEFAULT false,
	"DPMT_ID" uuid NOT NULL, 
    "CRTN_DATE" timestamp with time zone NOT NULL DEFAULT now(),
    "LAST_UPTD_DATE" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "MERIT_BADGE_PKEY" PRIMARY KEY ("BADGE_ID"),
    CONSTRAINT "MERIT_BADGE_NAME_KEY" UNIQUE ("BADGE_NAME")
);

CREATE TABLE IF NOT EXISTS public."MERIT_BADGE_MAIN_RQMT"
(
    "MAIN_RQMT_ID" uuid NOT NULL DEFAULT gen_random_uuid(),
    "BADGE_ID" uuid NOT NULL,
    "RQMT_DESC" text COLLATE pg_catalog."default" NOT NULL,
    "RQMT_NMBR" varchar(10) NOT NULL,
    "CRTN_DATE" timestamp with time zone NOT NULL DEFAULT now(),
    "LAST_UPTD_DATE" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "MERIT_BADGE_MAIN_RQMT_PKEY" PRIMARY KEY ("MAIN_RQMT_ID"),
    CONSTRAINT "MERIT_BADGE_MAIN_RQMT_BADGE_ID_RQMT_NMBR_KEY" UNIQUE ("BADGE_ID", "RQMT_NMBR")
);

CREATE TABLE IF NOT EXISTS public."MERIT_BADGE_SUB_RQMT"
(
    "SUB_RQMT_ID" uuid NOT NULL DEFAULT gen_random_uuid(),
    "MAIN_RQMT_ID" uuid NOT NULL,
    "SUB_RQMT_IDNF" varchar(10) NOT NULL,
    "SUB_RQMT_DESC" text COLLATE pg_catalog."default" NOT NULL,
    "CRTN_DATE" timestamp with time zone NOT NULL DEFAULT now(),
    "LAST_UPTD_DATE" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "MERIT_BADGE_SUB_RQMT_PKEY" PRIMARY KEY ("SUB_RQMT_ID"),
    CONSTRAINT "MERIT_BADGE_SUB_RQMT_MAIN_RQMT_ID_SUB_RQMT_IDNF_KEY" UNIQUE ("MAIN_RQMT_ID", "SUB_RQMT_IDNF")
);

CREATE TABLE IF NOT EXISTS public."SCOUT_BADGE"
(
    "SCOUT_BADGE_ID" uuid NOT NULL DEFAULT gen_random_uuid(),
    "SCOUT_ID" uuid NOT NULL,
    "BADGE_ID" uuid NOT NULL,
    "COMPLETED" boolean NOT NULL DEFAULT false,
    "CRTN_DATE" timestamp with time zone NOT NULL DEFAULT now(),
    "LAST_UPTD_DATE" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "SCOUT_BADGE_PKEY" PRIMARY KEY ("SCOUT_BADGE_ID"),
    CONSTRAINT "SCOUT_BADGE_SCOUT_ID_BADGE_ID_KEY" UNIQUE ("SCOUT_ID", "BADGE_ID")
);

CREATE TABLE IF NOT EXISTS public."SCOUT_BADGE_MAIN_RQMT"
(
    "SCOUT_BADGE_MAIN_RQMT_ID" uuid NOT NULL DEFAULT gen_random_uuid(),
    "SCOUT_BADGE_ID" uuid NOT NULL,
    "MAIN_RQMT_ID" uuid NOT NULL,
    "COMPLETED" boolean NOT NULL DEFAULT false,
    "CRTN_DATE" timestamp with time zone NOT NULL DEFAULT now(),
    "LAST_UPTD_DATE" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "SCOUT_BADGE_MAIN_RQMT_PKEY" PRIMARY KEY ("SCOUT_BADGE_MAIN_RQMT_ID"),
    CONSTRAINT "SCOUT_BADGE_MAIN_RQMT_SCOUT_BADGE_ID_MAIN_RQMT_ID_KEY" UNIQUE ("SCOUT_BADGE_ID", "MAIN_RQMT_ID")
);

CREATE TABLE IF NOT EXISTS public."SCOUT_BADGE_SUB_RQMT"
(
    "SCOUT_BADGE_SUB_RQMT_ID" uuid NOT NULL DEFAULT gen_random_uuid(),
    "SCOUT_BADGE_MAIN_RQMT_ID" uuid NOT NULL,
    "SUB_RQMT_ID" uuid NOT NULL,
    "COMPLETED" boolean NOT NULL DEFAULT false,
    "CRTN_DATE" timestamp with time zone NOT NULL DEFAULT now(),
    "LAST_UPTD_DATE" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "SCOUT_BADGE_SUB_RQMT_PKEY" PRIMARY KEY ("SCOUT_BADGE_SUB_RQMT_ID"),
    CONSTRAINT "SCOUT_BADGE_SUB_RQMT_MAIN_RQMT_ID_SUB_RQMT_ID_KEY" UNIQUE ("SCOUT_BADGE_MAIN_RQMT_ID", "SUB_RQMT_ID")
);

CREATE TABLE IF NOT EXISTS public."USERS"
(
    "USER_ID" uuid NOT NULL DEFAULT gen_random_uuid(),
    "USER_EMAIL" varchar(150) NOT NULL,
    "USER_FIRST_NAME" varchar(150) NOT NULL,
    "USER_LAST_NAME" varchar(150) NOT NULL,
    "USER_ROLE" varchar(150) NOT NULL,
    "EMP_ID" uuid,
    "SCOUT_LEADER_ID" uuid,
    "SCOUT_ID" uuid,
    "CRTN_DATE" timestamp with time zone NOT NULL DEFAULT now(),
    "LAST_UPTD_DATE" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "USERS_PKEY" PRIMARY KEY ("USER_ID"),
    CONSTRAINT "USERS_EMAIL_KEY" UNIQUE ("USER_EMAIL")
);


ALTER TABLE IF EXISTS public."USERS"
    ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS public."CAMP_DPMT"
    ADD CONSTRAINT "FK_DPMT_HEAD" FOREIGN KEY ("DPMT_HEAD_ID")
    REFERENCES public."EMPLOYEE" ("EMP_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public."EMPLOYEE"
    ADD CONSTRAINT "EMPLOYEE_DPMT_ID_FKEY" FOREIGN KEY ("DPMT_ID")
    REFERENCES public."CAMP_DPMT" ("DPMT_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."MERIT_BADGE_MAIN_RQMT"
    ADD CONSTRAINT "MERIT_BADGE_MAIN_RQMT_BADGE_ID_FKEY" FOREIGN KEY ("BADGE_ID")
    REFERENCES public."MERIT_BADGE" ("BADGE_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."MERIT_BADGE_SUB_RQMT"
    ADD CONSTRAINT "MERIT_BADGE_SUB_RQMT_MAIN_RQMT_ID_FKEY" FOREIGN KEY ("MAIN_RQMT_ID")
    REFERENCES public."MERIT_BADGE_MAIN_RQMT" ("MAIN_RQMT_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."SCOUT"
    ADD CONSTRAINT "SCOUT_TROOP_ID_FKEY" FOREIGN KEY ("TROOP_ID")
    REFERENCES public."TROOP" ("TROOP_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."SCOUT_BADGE"
    ADD CONSTRAINT "SCOUT_BADGE_BADGE_ID_FKEY" FOREIGN KEY ("BADGE_ID")
    REFERENCES public."MERIT_BADGE" ("BADGE_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."SCOUT_BADGE"
    ADD CONSTRAINT "SCOUT_BADGE_SCOUT_ID_FKEY" FOREIGN KEY ("SCOUT_ID")
    REFERENCES public."SCOUT" ("SCOUT_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."SCOUT_BADGE_MAIN_RQMT"
    ADD CONSTRAINT "SCOUT_BADGE_MAIN_RQMT_MAIN_RQMT_ID_FKEY" FOREIGN KEY ("MAIN_RQMT_ID")
    REFERENCES public."MERIT_BADGE_MAIN_RQMT" ("MAIN_RQMT_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."SCOUT_BADGE_MAIN_RQMT"
    ADD CONSTRAINT "SCOUT_BADGE_MAIN_RQMT_SCOUT_BADGE_ID_FKEY" FOREIGN KEY ("SCOUT_BADGE_ID")
    REFERENCES public."SCOUT_BADGE" ("SCOUT_BADGE_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."SCOUT_BADGE_SUB_RQMT"
    ADD CONSTRAINT "SCOUT_BADGE_SUB_RQMT_MAIN_RQMT_ID_FKEY" FOREIGN KEY ("MAIN_RQMT_ID")
    REFERENCES public."SCOUT_BADGE_MAIN_RQMT" ("SCOUT_BADGE_MAIN_RQMT_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."SCOUT_BADGE_SUB_RQMT"
    ADD CONSTRAINT "SCOUT_BADGE_SUB_RQMT_SUB_RQMT_ID_FKEY" FOREIGN KEY ("SUB_RQMT_ID")
    REFERENCES public."MERIT_BADGE_SUB_RQMT" ("SUB_RQMT_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."SCOUT_LEADER"
    ADD CONSTRAINT "SCOUT_LEADER_TROOP_ID_FKEY" FOREIGN KEY ("TROOP_ID")
    REFERENCES public."TROOP" ("TROOP_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


--ALTER TABLE IF EXISTS public.troop
--    ADD CONSTRAINT fk_troop_current_leader FOREIGN KEY (leader_id)
--    REFERENCES public.scout_leader (id) MATCH SIMPLE
--    ON UPDATE NO ACTION
--    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public."USERS"
    ADD CONSTRAINT "USERS_EMPLOYEE_ID_FKEY" FOREIGN KEY ("EMP_ID")
    REFERENCES public."EMPLOYEE" ("EMP_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public."USERS"
    ADD CONSTRAINT "USERS_SCOUT_ID_FKEY" FOREIGN KEY ("SCOUT_ID")
    REFERENCES public."SCOUT" ("SCOUT_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public."USERS"
    ADD CONSTRAINT "USERS_SCOUT_LEADER_ID_FKEY" FOREIGN KEY ("SCOUT_LEADER_ID")
    REFERENCES public."SCOUT_LEADER" ("SCOUT_LEADER_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;